#MODULO TIME
#modulo que se debe importar 
'''day''' #para referirse a los dias

'''month'''#para meses

'''year'''#para años

#escribe un programa que calcule cuandos dias faltan para navidad utilizar la funcion date del
#modulo datatime y la fecha de navidad como referencia

#crea una funcion que recibe como parametros la fecha de nacimiento y la fecha actual y devuelva la edad
#de la persona en años cumplidos

#escribe un programa que solicite al usuario que intridusca una efcha en un formato dias/meses/años
#la convierte a un objeto de la clase date del modulo datetime y muestra por pantalla el dia de la semana correspondiente

#escribe un programa con el modulo datetime que funcione como alarma y escribe una operacion matematica que haga que se ejecute  despues de 20 segundos

#escribe una fecha en formato  iso

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

#modulo os
#interfaz para el sistema operativo
#mkdir crea un directorio

#------------------------------------------------------------------------------------------------------------------------------------------------------------------
#calendar


